#!/bin/bash

echo -e "------CPU and Memory Resources------"

cpu_load=`uptime | tail -c 17`
echo -e "CPU Average Load: $cpu_load"

free_RAM=`free -h | awk '{print $3}' | awk 'FNR==2'`
echo -e "Free RAM: $free_RAM"

echo -e "\n"
echo -e "------Network Connections------"

intf_1=`cat /proc/net/dev | awk '{print $1}' | awk 'FNR==3'`
intf_1_recv_bytes=`cat /proc/net/dev | awk '{print $2}' | awk 'FNR==3'`
intf_1_trans_bytes=`cat /proc/net/dev | awk '{print $10}' | awk 'FNR==3'`

intf_2=`cat /proc/net/dev | awk '{print $1}' | awk 'FNR==4'`
intf_2_recv_bytes=`cat /proc/net/dev | awk '{print $2}' | awk 'FNR==4'`
intf_2_trans_bytes=`cat /proc/net/dev | awk '{print $10}' | awk 'FNR==4'`

echo -e "$intf_1"
echo -e "\tBytes Received:   $intf_1_recv_bytes"
echo -e "\tBytes Trasmitted: $intf_1_trans_bytes"

echo -e "$intf_2"
echo -e "\tBytes Received:   $intf_2_recv_bytes"
echo -e "\tBytes Trasmitted: $intf_2_trans_bytes"

echo -e "\n"

#Ping google once and check for success or failure
if `ping -q -c 1 -W 1 www.google.com > /dev/null`;
then
  echo "Internet Connectivity: Yes"
else
  echo "Internet Connectivity: No"
fi

echo -e "\n"
echo -e "------Account Information------"

total_users=`cat /etc/passwd | wc -l`
active_users=`who | wc -l`

echo -e "Total Users: $total_users \t Number Active: $active_users"
echo -e "Shells:"
echo -e "\t/sbin/nologin: `cat /etc/passwd | grep "/sbin/nologin" | wc -l`"
echo -e "\t/bin/bash:     `cat /etc/passwd | grep "/bin/bash" | wc -l`"
echo -e "\t/bin/false:    `cat /etc/passwd | grep "/bin/false" | wc -l`"

echo -e "\n"

echo -e "------Filesystem Information------"
echo -e "Total Number of Files:       `find / -type f | wc -l`"
echo -e "Total Number of Directories: `find / -type d | wc -l`"


